site_name: NTTC (Name That Twitter Community!)
nav:
    - Home: index.md
    - Sampling Community-Detected Data: sample-data.md
    - Topic-Modeling: tm-comm-data.md
    - Processing Infomap data: infomap-examples.md
    - Community Likeness: comm-jacc.md
theme: readthedocs
